routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['lock']], function () {
    Route::get('/', 'EventController@index')->name('events.index');
    Route::redirect('/events', '/');
    Route::get('/events/create', 'EventController@create')->name('events.create');
    Route::post('/events', 'EventController@store')->name('events.store');
    Route::post('/events/image', 'EventController@uploadImage');
    Route::get('/events/{event}', 'EventController@show')->name('events.show');
    Route::get('/events/{event}/edit', 'EventController@edit')->name('events.edit')->middleware('auth');;
    Route::post('/events/{event}/edit', 'EventController@update')->name('events.update')->middleware('auth');;

    Route::put('/events/{event}', 'EventController@publish')->name('events.publish')->middleware('auth');
    Route::delete('/events/{event}', 'EventController@destroy')->name('events.destroy')->middleware('auth');


    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::resource('admin', 'OptionController')->only([
        'index', 'edit', 'update',
    ])->middleware('auth');

    Route::get('about', 'OptionController@about')->name('about');
});

Route::get('unlock', 'LoginController@locked')->name('locked');
Route::post('unlock', 'LoginController@unlock')->name('unlock');

app/Http/Controllers/OptionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Parsedown;

class OptionController extends Controller
{
    private const OPTIONS = [
        'site_name' => [
            'type' => 'text',
            'default' => 'We Are Agenda',
        ],
        'no_review' => [
            'type' => 'boolean',
            'default' => false,
        ],
        'publication_criteria' => [
            'type' => 'editor',
        ],
        'about_content' => [
            'type' => 'editor',
        ],
        'home_banner' => [
            'type' => 'editor',
            'default' => false,
        ],
        'locked' => [
            'type' => 'boolean',
            'default' => false,
        ],
        'locked_password' => [
            'type' => 'text',
        ],
        'locked_banner' => [
            'type' => 'editor',
        ],
    ];

    public static function getOption($name)
    {
        if (! in_array($name, array_keys(self::OPTIONS))) {
            abort(404);
        }

        $cacheKey = 'option_'.$name;
        $option = Cache::get($cacheKey);

        if (null !== $option) {
            return $option;
        }

        $option = DB::selectOne(
            'select value from options where name = ?',
            [$name]
        );

        if (null === $option) {
            if (! isset(self::OPTIONS[$name]['default'])) {
                return null;
            }

            Cache::put($cacheKey, self::OPTIONS[$name]['default']);

            return self::OPTIONS[$name]['default'];
        }

        Cache::put($cacheKey, $option->value);

        return $option->value;
    }

    public function index()
    {
        $options = [];
        foreach (self::OPTIONS as $name => $option) {

            $options[$name]  = $option['type'] === 'boolean'
                ? __('admin.bool.'.var_export(self::getOption($name), true))
                : self::getOption($name);
        }

        return view('options.index', ['options' => $options]);
    }

    private function checkIfExist(string $name)
    {
        if (! in_array($name, array_keys(self::OPTIONS))) {
            abort(404);
        }
    }

    public function edit($name)
    {
        $this->checkIfExist($name);
        $type = self::OPTIONS[$name]['type'];

        if (! view()->exists('options.inputs.'.$type)) {
            abort(500);
        }

        return view('options.inputs.'.$type, ['name' => $name, 'value' => self::getOption($name)]);
    }

    public function update(Request $request, $name)
    {
        $this->checkIfExist($name);

        $type = self::OPTIONS[$name]['type'];
        $value = $request->get('value');

        if ('boolean' === $type) {
            $value = 'on' === $value;
        }

        if (null === DB::selectOne('select name from options where name = ?', [$name])) {
            DB::insert('insert into options (name, value) values (?, ?)', [$name, $value]);
        } else {
            DB::update('update options set value = ? where name = ?', [$value, $name]);
        }
        Cache::put('option_'.$name, $value);

        return redirect()->route('admin.edit', ['admin' => $name]);
    }

    public static function getBanner($name)
    {
        $parsedown = new Parsedown();

        return $parsedown->setSafeMode(true)->text(self::getOption($name.'_banner'));
    }

    public function about(Parsedown $parsedown)
    {
        return view('about', [
            'publicationCriteria' => $parsedown->setSafeMode(true)->text(self::getOption('publication_criteria')),
            'about' => $parsedown->setSafeMode(true)->text(self::getOption('about_content')),
        ]);
    }
}

resources/views/options/edit.blade.php
@extends('layouts.app')

@section('title', __('admin.edit').' '.$name)

@section('content')
    <form
        action="{{route('admin.update', ['admin' => $name])}}"
        method="post"
    >
        <h1><label class="font-semibold text-3xl" for="value">@lang('admin.edit') {{ $name }}</label></h1>
        <p>@lang('admin.optionDescription.'.$name)</p>

        @yield('inputs')

        <input type="submit" class="mt-2 block btn btn blue" value="@lang('admin.update')">
        @csrf
        @method('PATCH')
    </form>
@endsection

@push('scripts')
    <script src="{{ mix('js/edit.js') }}" type="module"></script>
@endpush

resources/views/options/index.blade.php
@extends('layouts.app')

@section('title', __('nav.admin'))

@section('content')
    <h1 class="font-semibold text-center text-3xl mb-3">@lang('nav.admin')</h1>

    <table class="w-full">
        <thead>
        <tr>
            <th class="px-4 py-2">@lang('admin.option')</th>
            <th class="px-4 py-2">@lang('admin.description')</th>
            <th class="px-4 py-2">@lang('admin.value')</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($options as $name => $value)
            <tr>
                <td class="border px-4 py-2">
                    <a class="underline text-orange-700 orahover:text-black" href="{{ route('admin.edit', ['admin' => $name]) }}">
                        {{ $name }}
                    </a>
                </td>
                <td class="border px-4 py-2">@lang('admin.optionDescription.'.$name)</td>
                <td class="border px-4 py-2"><code>{{ $value }}</code></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection