routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['lock']], function () {
    Route::get('/', 'EventController@index')->name('events.index');
    Route::redirect('/events', '/');
    Route::get('/events/create', 'EventController@create')->name('events.create');
    Route::post('/events', 'EventController@store')->name('events.store');
    Route::post('/events/image', 'EventController@uploadImage');
    Route::get('/events/{event}', 'EventController@show')->name('events.show');
    Route::get('/events/{event}/edit', 'EventController@edit')->name('events.edit')->middleware('auth');;
    Route::post('/events/{event}/edit', 'EventController@update')->name('events.update')->middleware('auth');;

    Route::put('/events/{event}', 'EventController@publish')->name('events.publish')->middleware('auth');
    Route::delete('/events/{event}', 'EventController@destroy')->name('events.destroy')->middleware('auth');


    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::resource('admin', 'OptionController')->only([
        'index', 'edit', 'update',
    ])->middleware('auth');

    Route::get('about', 'OptionController@about')->name('about');
});

Route::get('unlock', 'LoginController@locked')->name('locked');
Route::post('unlock', 'LoginController@unlock')->name('unlock');

resources/views/layouts/app.blade.php
@extends('layouts.html')

@section('body')
    <header>
        <nav class="bg-orange-700 text-white px-4">
            <ul class="flex flex-wrap py-4">
                <li class="flex items-center flex-shrink-0 mr-6">
                    <a href="{{url('/')}}" class="font-semibold text-xl">
                        {{ \App\Http\Controllers\OptionController::getOption('site_name') }}
                    </a>
                </li>
                <li class="flex items-center flex-shrink-0 mr-6">
                    <a href="{{route('events.create')}}">@lang('nav.publish')</a>
                </li>
                <li class="flex items-center flex-shrink-0 mr-6">
                    <a href="{{route('about')}}">@lang('nav.about')</a>
                </li>
                @if(Auth::check())
                    <li class="flex items-center flex-shrink-0 mr-6">
                        <a href="{{route('admin.index')}}">@lang('nav.admin')</a>
                    </li>
                    <form action="{{route('logout')}}" method="POST" class="flex items-center flex-shrink-0 mr-6">
                        @csrf
                        <input
                            type="submit"
                            class="bg-transparent cursor-pointer"
                            value="@lang('nav.logout')"
                        >
                    </form>
                @endif
            </ul>
        </nav>
    </header>
    <main class="container mx-auto p-3">
        @yield('content')
    </main>
    @stack('scripts')
@endsection

resources/views/layouts/html.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') - {{ \App\Http\Controllers\OptionController::getOption('site_name') }}</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
@yield('body')
</body>
</html>